DROP TABLE IF EXISTS approvals;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS users;

-- Identifiers are deliberately left unquoted. Postgres folds unquoted names to
-- lower case in DDL and in queries alike, so the camelCase columns the apps
-- already query (userId, expenseId) keep resolving without any SQL changes.
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL
);

CREATE TABLE expenses (
    -- BY DEFAULT, not ALWAYS: the seed and test fixtures insert explicit ids.
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userId INTEGER NOT NULL,
    -- DOUBLE PRECISION, not NUMERIC: NUMERIC arrives in Python as Decimal,
    -- which the service layer and JSON encoder would both have to learn.
    amount DOUBLE PRECISION NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL CHECK (
        category IN (
            'TRAVEL',
            'MEALS',
            'LODGING',
            'OFFICE_SUPPLIES',
            'EQUIPMENT',
            'SOFTWARE',
            'TRAINING',
            'OTHER'
        )
    ),
    -- Kept TEXT rather than DATE: both apps read and write ISO-8601 strings, and
    -- those compare correctly under BETWEEN lexicographically.
    date TEXT NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id)
);

CREATE TABLE approvals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expenseId INTEGER NOT NULL UNIQUE,
    status TEXT NOT NULL, -- pending, approved or denied?
    reviewer INTEGER,
    comment TEXT,
    review_date TEXT,
    FOREIGN KEY (expenseId) REFERENCES expenses(id),
    FOREIGN KEY (reviewer) REFERENCES users(id)
);

-- The manager review path filters approvals by expenseId on every write, and
-- the UNIQUE constraint above already indexes that. These two cover the read
-- paths that drove the load-test latency.
-- Keep semicolons out of comments in this file. The Java test fixtures load it
-- by splitting on the statement separator, and one inside a comment splits a
-- statement in half.
CREATE INDEX idx_expenses_userid ON expenses(userId);
CREATE INDEX idx_expenses_category ON expenses(category);
