SET SEARCH_PATH TO "public 2";
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ; 
BEGIN;

UPDATE accounts
SET balance = 1500
WHERE account_id = 1;

COMMIT;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN;
INSERT INTO accounts
VALUES(4, 'David',900);
COMMIT;

