services:
  backend:
    build:
      context: ./backend # Path to your spring project
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge